# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ? adp-manual-test
  : build:
      target: development
    ports:
      - "3007:3007"
    volumes:
      - ./src/Adp.Manual.Test.Api:/home/dotnet/src/Adp.Manual.Test.Api
      - ./src/Adp.Manual.Test.Core:/home/dotnet/src/Adp.Manual.Test.Core