services:
  ? adp-manual-test
  : build:
      target: development
    image: adp-manual-test-development
    container_name: adp-manual-test-test
    user: root
    entrypoint: sh -c "cd /home/dotnet && chown -R dotnet:dotnet . && su dotnet -c 'dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./test-output/'"
    volumes:
      - ./Adp.Manual.Test.sln:/home/dotnet/Adp.Manual.Test.sln
      - ./src/Adp.Manual.Test.Core:/home/dotnet/src/Adp.Manual.Test.Core
      - ./test/Adp.Manual.Test.Core.Tests:/home/dotnet/test/Adp.Manual.Test.Core.Tests
      - ./src/Adp.Manual.Test.Api:/home/dotnet/src/Adp.Manual.Test.Api
      - ./test/Adp.Manual.Test.Api.Tests:/home/dotnet/test/Adp.Manual.Test.Api.Tests
      - ./test/Adp.Manual.Test.Api.Tests/test-output:/home/dotnet/test/Adp.Manual.Test.Api.Tests/test-output
      - ./test/Adp.Manual.Test.Core.Tests/test-output:/home/dotnet/test/Adp.Manual.Test.Core.Tests/test-output
